metricbeat.modules:

#------------------------------- MongoDB Module -------------------------------

- module: mongodb
  enabled: true
  metricsets: ["dbstats", "status"]
  period: 5s
  hosts: ["mongodb:27017"]

#-------------------------- Elasticsearch output ------------------------------
output.elasticsearch:
  username: "metricbeat_anonymous_user"
  #password: ""
  hosts: ["${HOST_ELASTICSEARCH}"]

setup.kibana:
  host: "${HOST_KIBANA}"

#============================== Dashboards =====================================
# These settings control loading the sample dashboards to the Kibana index. Loading
# the dashboards is disabled by default and can be enabled either by setting the
# options here, or by using the `-setup` CLI flag.
setup.dashboards.enabled: true

logging.level: warning
logging.to_files: true
logging.to_syslog: false
logging.files:
  path: /var/log/metricbeat
  name: metricbeat.log
  keepfiles: 2
  permissions: 0644